/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as OrganizationsNewRouteImport } from './routes/organizations/new'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as OrganizationsOrganizationIdIndexRouteImport } from './routes/organizations/$organizationId/index'
import { Route as OrganizationsOrganizationIdSettingsRouteImport } from './routes/organizations/$organizationId/settings'
import { Route as OrganizationsOrganizationIdDashboardRouteImport } from './routes/organizations/$organizationId/dashboard'
import { Route as OrganizationsOrganizationIdCompaniesIndexRouteImport } from './routes/organizations/$organizationId/companies/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/journal-entries/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRouteImport } from './routes/organizations/$organizationId/companies/$companyId/accounts/index'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRouteImport } from './routes/organizations/$organizationId/companies/$companyId/journal-entries/new'
import { Route as OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRouteImport } from './routes/organizations/$organizationId/companies/$companyId/accounts/new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdIndexRoute =
  OrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdSettingsRoute =
  OrganizationsOrganizationIdSettingsRouteImport.update({
    id: '/organizations/$organizationId/settings',
    path: '/organizations/$organizationId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdDashboardRoute =
  OrganizationsOrganizationIdDashboardRouteImport.update({
    id: '/organizations/$organizationId/dashboard',
    path: '/organizations/$organizationId/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdCompaniesIndexRoute =
  OrganizationsOrganizationIdCompaniesIndexRouteImport.update({
    id: '/organizations/$organizationId/companies/',
    path: '/organizations/$organizationId/companies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdIndexRouteImport.update({
    id: '/organizations/$organizationId/companies/$companyId/',
    path: '/organizations/$organizationId/companies/$companyId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRouteImport.update(
    {
      id: '/organizations/$organizationId/companies/$companyId/journal-entries/',
      path: '/organizations/$organizationId/companies/$companyId/journal-entries/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRouteImport.update({
    id: '/organizations/$organizationId/companies/$companyId/accounts/',
    path: '/organizations/$organizationId/companies/$companyId/accounts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRouteImport.update(
    {
      id: '/organizations/$organizationId/companies/$companyId/journal-entries/new',
      path: '/organizations/$organizationId/companies/$companyId/journal-entries/new',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute =
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRouteImport.update({
    id: '/organizations/$organizationId/companies/$companyId/accounts/new',
    path: '/organizations/$organizationId/companies/$companyId/accounts/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/organizations/$organizationId/dashboard': typeof OrganizationsOrganizationIdDashboardRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/companies': typeof OrganizationsOrganizationIdCompaniesIndexRoute
  '/organizations/$organizationId/companies/$companyId': typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute
  '/organizations/$organizationId/companies/$companyId/accounts/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute
  '/organizations/$organizationId/companies/$companyId/accounts': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/organizations/$organizationId/dashboard': typeof OrganizationsOrganizationIdDashboardRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/companies': typeof OrganizationsOrganizationIdCompaniesIndexRoute
  '/organizations/$organizationId/companies/$companyId': typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute
  '/organizations/$organizationId/companies/$companyId/accounts/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute
  '/organizations/$organizationId/companies/$companyId/accounts': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/organizations/$organizationId/dashboard': typeof OrganizationsOrganizationIdDashboardRoute
  '/organizations/$organizationId/settings': typeof OrganizationsOrganizationIdSettingsRoute
  '/organizations/$organizationId/': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/companies/': typeof OrganizationsOrganizationIdCompaniesIndexRoute
  '/organizations/$organizationId/companies/$companyId/': typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute
  '/organizations/$organizationId/companies/$companyId/accounts/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/new': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute
  '/organizations/$organizationId/companies/$companyId/accounts/': typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute
  '/organizations/$organizationId/companies/$companyId/journal-entries/': typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/$'
    | '/organizations/new'
    | '/organizations'
    | '/organizations/$organizationId/dashboard'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/companies'
    | '/organizations/$organizationId/companies/$companyId'
    | '/organizations/$organizationId/companies/$companyId/accounts/new'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/new'
    | '/organizations/$organizationId/companies/$companyId/accounts'
    | '/organizations/$organizationId/companies/$companyId/journal-entries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/$'
    | '/organizations/new'
    | '/organizations'
    | '/organizations/$organizationId/dashboard'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/companies'
    | '/organizations/$organizationId/companies/$companyId'
    | '/organizations/$organizationId/companies/$companyId/accounts/new'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/new'
    | '/organizations/$organizationId/companies/$companyId/accounts'
    | '/organizations/$organizationId/companies/$companyId/journal-entries'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/api/$'
    | '/organizations/new'
    | '/organizations/'
    | '/organizations/$organizationId/dashboard'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/companies/'
    | '/organizations/$organizationId/companies/$companyId/'
    | '/organizations/$organizationId/companies/$companyId/accounts/new'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/new'
    | '/organizations/$organizationId/companies/$companyId/accounts/'
    | '/organizations/$organizationId/companies/$companyId/journal-entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiSplatRoute: typeof ApiSplatRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  OrganizationsOrganizationIdDashboardRoute: typeof OrganizationsOrganizationIdDashboardRoute
  OrganizationsOrganizationIdSettingsRoute: typeof OrganizationsOrganizationIdSettingsRoute
  OrganizationsOrganizationIdIndexRoute: typeof OrganizationsOrganizationIdIndexRoute
  OrganizationsOrganizationIdCompaniesIndexRoute: typeof OrganizationsOrganizationIdCompaniesIndexRoute
  OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/': {
      id: '/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/settings': {
      id: '/organizations/$organizationId/settings'
      path: '/organizations/$organizationId/settings'
      fullPath: '/organizations/$organizationId/settings'
      preLoaderRoute: typeof OrganizationsOrganizationIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/dashboard': {
      id: '/organizations/$organizationId/dashboard'
      path: '/organizations/$organizationId/dashboard'
      fullPath: '/organizations/$organizationId/dashboard'
      preLoaderRoute: typeof OrganizationsOrganizationIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/companies/': {
      id: '/organizations/$organizationId/companies/'
      path: '/organizations/$organizationId/companies'
      fullPath: '/organizations/$organizationId/companies'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/companies/$companyId/': {
      id: '/organizations/$organizationId/companies/$companyId/'
      path: '/organizations/$organizationId/companies/$companyId'
      fullPath: '/organizations/$organizationId/companies/$companyId'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/companies/$companyId/journal-entries/': {
      id: '/organizations/$organizationId/companies/$companyId/journal-entries/'
      path: '/organizations/$organizationId/companies/$companyId/journal-entries'
      fullPath: '/organizations/$organizationId/companies/$companyId/journal-entries'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/companies/$companyId/accounts/': {
      id: '/organizations/$organizationId/companies/$companyId/accounts/'
      path: '/organizations/$organizationId/companies/$companyId/accounts'
      fullPath: '/organizations/$organizationId/companies/$companyId/accounts'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/companies/$companyId/journal-entries/new': {
      id: '/organizations/$organizationId/companies/$companyId/journal-entries/new'
      path: '/organizations/$organizationId/companies/$companyId/journal-entries/new'
      fullPath: '/organizations/$organizationId/companies/$companyId/journal-entries/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/companies/$companyId/accounts/new': {
      id: '/organizations/$organizationId/companies/$companyId/accounts/new'
      path: '/organizations/$organizationId/companies/$companyId/accounts/new'
      fullPath: '/organizations/$organizationId/companies/$companyId/accounts/new'
      preLoaderRoute: typeof OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiSplatRoute: ApiSplatRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  OrganizationsOrganizationIdDashboardRoute:
    OrganizationsOrganizationIdDashboardRoute,
  OrganizationsOrganizationIdSettingsRoute:
    OrganizationsOrganizationIdSettingsRoute,
  OrganizationsOrganizationIdIndexRoute: OrganizationsOrganizationIdIndexRoute,
  OrganizationsOrganizationIdCompaniesIndexRoute:
    OrganizationsOrganizationIdCompaniesIndexRoute,
  OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute:
    OrganizationsOrganizationIdCompaniesCompanyIdIndexRoute,
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute:
    OrganizationsOrganizationIdCompaniesCompanyIdAccountsNewRoute,
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute:
    OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesNewRoute,
  OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute:
    OrganizationsOrganizationIdCompaniesCompanyIdAccountsIndexRoute,
  OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute:
    OrganizationsOrganizationIdCompaniesCompanyIdJournalEntriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
